/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Samuel
 */
public class CadastroPacienteView extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPacienteView
     */
    public CadastroPacienteView() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            pesquisa();
        } catch (SQLException ex) {
            Logger.getLogger(ConsultaFuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        urgenciaComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        medicoTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        quarto402Button = new javax.swing.JRadioButton();
        quarto401Button = new javax.swing.JRadioButton();
        quarto403Button = new javax.swing.JRadioButton();
        quarto502Button = new javax.swing.JRadioButton();
        quarto503Button = new javax.swing.JRadioButton();
        quarto501Button = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        cpfTextField = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cidadeTextField = new javax.swing.JTextField();
        ruaTextField = new javax.swing.JTextField();
        numeroRuaTextField = new javax.swing.JTextField();
        telefoneTextField = new javax.swing.JFormattedTextField();
        nomeTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cadastrarButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Paciente"));

        jLabel2.setText("Urgência:");

        urgenciaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emergência", "Muito Urgente", "Urgente", "Pouco Urgente", "Não Urgente" }));
        urgenciaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urgenciaComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Médico (CRM):");

        jLabel11.setText("Quartos:");

        buttonGroup1.add(quarto402Button);
        quarto402Button.setText("402");
        quarto402Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quarto402ButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(quarto401Button);
        quarto401Button.setText("401");
        quarto401Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quarto401ButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(quarto403Button);
        quarto403Button.setText("403");
        quarto403Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quarto403ButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(quarto502Button);
        quarto502Button.setText("502");
        quarto502Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quarto502ButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(quarto503Button);
        quarto503Button.setText("503");
        quarto503Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quarto503ButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(quarto501Button);
        quarto501Button.setText("501");
        quarto501Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quarto501ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(urgenciaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(quarto401Button)
                    .addComponent(quarto501Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quarto402Button)
                            .addComponent(quarto502Button)
                            .addComponent(jLabel1))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabel9))
                            .addComponent(quarto403Button)
                            .addComponent(quarto503Button))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(medicoTextField))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(urgenciaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medicoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(40, 40, 40)))
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quarto402Button)
                    .addComponent(quarto401Button)
                    .addComponent(quarto403Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quarto502Button)
                    .addComponent(quarto503Button)
                    .addComponent(quarto501Button))
                .addContainerGap())
        );

        jLabel3.setText("Telefone:");

        try {
            cpfTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        jLabel4.setText("Cidade:");

        jLabel5.setText("Rua:");

        jLabel6.setText("Nº:");

        ruaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruaTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(numeroRuaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cidadeTextField)
                    .addComponent(ruaTextField)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(numeroRuaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        try {
            telefoneTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setText("CPF:");

        jLabel8.setText("Nome:");

        cadastrarButton.setText("Cadastrar");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpfTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(telefoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarButton)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void urgenciaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urgenciaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urgenciaComboBoxActionPerformed

    private void ruaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruaTextFieldActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ImageIcon icon = new ImageIcon("src/View/Imagens/searchIcon.png");
        setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowActivated

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        String insertPessoa = "INSERT INTO pessoa(cpf,nome,telefone,cidade,rua,numero_rua) VALUES"
                + " ('" + cpfTextField.getText() + "','" + nomeTextField.getText() + "','"
                + telefoneTextField.getText() + "','" + cidadeTextField.getText() + "','"
                + ruaTextField.getText() + "'," + numeroRuaTextField.getText() + ");";
        String insertPaciente = "INSERT INTO paciente"
                + "(fk_pessoa_cpf,fk_medico_crm,fk_andar_numero_andar,fk_quarto_numero_quarto,urgencia,data_internacao) VALUES"
                + " ('" + cpfTextField.getText() + "','" + medicoTextField.getText() + "'," + getAndar() + "," + getQuarto()
                + ",'" + getUrgencia() + "', current_date);";

        try {
            //  System.out.println("inicio coenxao");
            //  System.out.println("" + CPFTextField.getText() + "");
            Connection conexao = new Conexao().getConnection();
            PreparedStatement statementPessoa = conexao.prepareStatement(insertPessoa);
            PreparedStatement statementPaciente = conexao.prepareStatement(insertPaciente);
            statementPessoa.execute();
            statementPaciente.execute();
            statementPessoa.close();
            statementPaciente.close();
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroFuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível  realizar a inserção!\n" + ex.toString(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cadastrarButtonActionPerformed


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void quarto401ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quarto401ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quarto401ButtonActionPerformed

    private void quarto402ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quarto402ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quarto402ButtonActionPerformed

    private void quarto403ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quarto403ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quarto403ButtonActionPerformed

    private void quarto501ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quarto501ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quarto501ButtonActionPerformed

    private void quarto502ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quarto502ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quarto502ButtonActionPerformed

    private void quarto503ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quarto503ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quarto503ButtonActionPerformed

    private int getAndar() {
        int andar = 0;
        if (quarto401Button.isSelected() || quarto402Button.isSelected() || quarto403Button.isSelected()) {
            andar = 4;
        } else if (quarto501Button.isSelected() || quarto502Button.isSelected() || quarto503Button.isSelected()) {
            andar = 5;
        }
        return andar;
    }

    private int getQuarto() {
        int quarto = 0;
        if (quarto401Button.isSelected()) {
            quarto = 401;
        }
        if (quarto402Button.isSelected()) {
            quarto = 402;
        }
        if (quarto403Button.isSelected()) {
            quarto = 403;
        }
        if (quarto501Button.isSelected()) {
            quarto = 501;
        }
        if (quarto502Button.isSelected()) {
            quarto = 502;
        }
        if (quarto503Button.isSelected()) {
            quarto = 503;
        }
        return quarto;
    }

    private char getUrgencia() {
        char urgencia = '0';
        if (urgenciaComboBox.getSelectedIndex() == 0) {
            urgencia = 'E';
        }
        if (urgenciaComboBox.getSelectedIndex() == 1) {
            urgencia = 'D';
        }
        if (urgenciaComboBox.getSelectedIndex() == 2) {
            urgencia = 'C';
        }
        if (urgenciaComboBox.getSelectedIndex() == 3) {
            urgencia = 'B';
        }
        if (urgenciaComboBox.getSelectedIndex() == 4) {
            urgencia = 'A';
        }
        return urgencia;
    }

    private void pesquisa() throws SQLException {
        String sql = "SELECT fk_quarto_numero_quarto FROM paciente ORDER BY fk_quarto_numero_quarto ASC";
        Connection conexao = new Conexao().getConnection();
        PreparedStatement statementPessoa = conexao.prepareStatement(sql);
        // ArrayList<Integer> quartos = new ArrayList<Integer>();
        statementPessoa.execute();
        ResultSet resultSet = statementPessoa.getResultSet();
        while (resultSet.next()) {
            if (resultSet.getInt("fk_quarto_numero_quarto") == 401) {
                quarto401Button.setEnabled(false);
            }
            if (resultSet.getInt("fk_quarto_numero_quarto") == 402) {
                quarto402Button.setEnabled(false);
            }
            if (resultSet.getInt("fk_quarto_numero_quarto") == 403) {
                quarto403Button.setEnabled(false);
            }
            if (resultSet.getInt("fk_quarto_numero_quarto") == 501) {
                quarto501Button.setEnabled(false);
            }
            if (resultSet.getInt("fk_quarto_numero_quarto") == 502) {
                quarto502Button.setEnabled(false);
            }
            if (resultSet.getInt("fk_quarto_numero_quarto") == 503) {
                quarto503Button.setEnabled(false);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPacienteView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JTextField cidadeTextField;
    private javax.swing.JFormattedTextField cpfTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField medicoTextField;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JTextField numeroRuaTextField;
    private javax.swing.JRadioButton quarto401Button;
    private javax.swing.JRadioButton quarto402Button;
    private javax.swing.JRadioButton quarto403Button;
    private javax.swing.JRadioButton quarto501Button;
    private javax.swing.JRadioButton quarto502Button;
    private javax.swing.JRadioButton quarto503Button;
    private javax.swing.JTextField ruaTextField;
    private javax.swing.JFormattedTextField telefoneTextField;
    private javax.swing.JComboBox<String> urgenciaComboBox;
    // End of variables declaration//GEN-END:variables
}
